/**
 * This is class test using JUnit for the trigonometric functions created in Functions.java.
 *
 * @author ASE Lab Group 12
 * Abhee Baboo Hudani 	( 110024036 )
 * Deep Patel 		    ( 110020706 )
 * @version 1.0.0
 */

package com.trigonometric;

import static com.trigonometric.Helper.factorial;
import static com.trigonometric.Helper.power;
import static org.junit.jupiter.api.Assertions.*;

import com.trigonometric.exceptions.FactorialException;
import com.trigonometric.exceptions.PowerException;
import org.junit.jupiter.api.Test;

class HelperTest {

    static final double decimalValue = 0.0001;

    // Power Testing : It will compare and check the power value generated by function with Math.pow
    @Test
    void powerTesting() throws PowerException {
        assertEquals(Math.pow(2, 7), power(2, 7));
    }

    // Factorial Testing : It will compare and check the factorial value generated by function with manually written value
    @Test
    void factorialTesting() throws FactorialException {
        assertEquals(40320, factorial(8));
    }

    // Degree Conversion Testing : It will compare and check the converted degree value generated by function with Math.toRadians
    @Test
    void convertDegreeToRadianTesting() {
        assertEquals(
                Math.toRadians(45),
                Helper.convertDegreeToRadian(45),
                decimalValue
        );
    }
}
